import React,{useEffect,useMemo,useState} from 'react';
import {levels} from './data/levels'; import {subjects} from './data/subjects'; import {suggestCurriculum,generateProject,generateClasses} from './services/abpGenerator'; import {exportWord} from './services/wordExporter'; import Field from './components/Field';
const initial={levels:[],classes:12,subjects:[],school:'',partners:'',responsible:'',collaborators:'',name:'',idea:'',description:'',product:'',challenge:''};
export default function App(){
 const [input,setInput]=useState(()=>JSON.parse(localStorage.getItem('abp-input')||'null')||initial); const [project,setProject]=useState(null); const [oas,setOas]=useState([]); const [classes,setClasses]=useState([]); const [tab,setTab]=useState('identificacion'); const [saved,setSaved]=useState(false);
 useEffect(()=>localStorage.setItem('abp-input',JSON.stringify(input)),[input]);
 const suggestions=useMemo(()=>suggestCurriculum(input),[input]);
 const set=(k,v)=>setInput(x=>({...x,[k]:v})); const toggle=(k,v)=>set(k,input[k].includes(v)?input[k].filter(x=>x!==v):[...input[k],v]);
 function generate(){const p=generateProject(input);const chosen=suggestions.slice(0,Math.min(6,suggestions.length));setProject(p);setOas(chosen);setClasses(generateClasses(input,p,chosen));setTab('proyecto');}
 function regenerateClasses(){if(project)setClasses(generateClasses(input,project,oas));}
 function demo(){setInput({...initial,levels:['5° básico','6° básico'],classes:12,subjects:['Ciencias Naturales','Historia, Geografía y Ciencias Sociales','Tecnología','Orientación','Lenguaje y Comunicación'],school:'Escuela de ejemplo',partners:'Comunidad local',responsible:'Docente responsable',name:'Un bosque que aprendemos a cuidar',idea:'crear un espacio de aprendizaje con árboles y plantas nativas en la escuela',product:'un espacio vivo de aprendizaje y un sistema de cuidado y comunicación del proyecto',challenge:'¿Cómo podemos transformar un espacio de la escuela en un lugar vivo para aprender, cuidar el territorio y compartir nuestros aprendizajes?',description:'Experiencia interdisciplinaria situada en el territorio.'});setSaved(false);}
 const tabs=[['identificacion','1. Identificación'],['proyecto','2. Diseño ABP'],['curriculo','3. Currículo'],['clases','4. Clases'],['evaluacion','5. Evaluación'],['revision','6. Revisión']];
 return <div className="app"><header><div><div className="eyebrow">DISEÑO PEDAGÓGICO</div><h1>PROYECTO ABP <b>INTERDISCIPLINARIO</b></h1><p>Del desafío a la evidencia. Diseña, revisa y exporta tu proyecto.</p></div><div className="actions"><button className="ghost" onClick={demo}>Cargar ejemplo</button>{project&&<button className="primary" onClick={()=>exportWord({input,project,oas,classes})}>Exportar Word</button>}</div></header>
 <nav>{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 <main>
 {tab==='identificacion'&&<section className="panel"><div className="sectionhead"><div><span className="kicker">PUNTO DE PARTIDA</span><h2>Identificación del proyecto</h2><p>Completa lo esencial. El sistema organizará la propuesta y dejará las decisiones pedagógicas en tus manos.</p></div></div>
 <div className="grid two"><Field label="Nivel *"><div className="chips">{levels.map(x=><button type="button" key={x} className={input.levels.includes(x)?'chip selected':'chip'} onClick={()=>toggle('levels',x)}>{x}</button>)}</div></Field><Field label="Duración estimada *"><input type="number" min="1" value={input.classes} onChange={e=>set('classes',e.target.value)}/><small>Número total de clases.</small></Field></div>
 <Field label="Asignaturas involucradas *"><div className="chips">{subjects.map(x=><button type="button" key={x} className={input.subjects.includes(x)?'chip selected':'chip'} onClick={()=>toggle('subjects',x)}>{x}</button>)}</div></Field>
 <div className="grid two"><Field label="Escuela *"><input value={input.school} onChange={e=>set('school',e.target.value)} /></Field><Field label="Socios colaboradores"><input value={input.partners} onChange={e=>set('partners',e.target.value)} placeholder="Familias, organizaciones, especialistas…"/></Field><Field label="Responsable del proyecto *"><input value={input.responsible} onChange={e=>set('responsible',e.target.value)}/></Field><Field label="Colaboradores"><input value={input.collaborators} onChange={e=>set('collaborators',e.target.value)}/></Field><Field label="Nombre del proyecto *"><input value={input.name} onChange={e=>set('name',e.target.value)}/></Field><Field label="Producto o resultado esperado"><input value={input.product} onChange={e=>set('product',e.target.value)} placeholder="¿Qué quedará hecho, creado o transformado?"/></Field></div>
 <Field label="Describe la idea de tu proyecto *"><textarea rows="4" value={input.idea} onChange={e=>set('idea',e.target.value)} placeholder="Cuéntalo con tus palabras. Por ejemplo: queremos crear un huerto escolar…"/></Field>
 <div className="grid two"><Field label="Contexto o necesidad detectada"><textarea rows="3" value={input.description} onChange={e=>set('description',e.target.value)}/></Field><Field label="Desafío o pregunta inicial (opcional)"><textarea rows="3" value={input.challenge} onChange={e=>set('challenge',e.target.value)}/></Field></div>
 <div className="footerbar"><span>{input.levels.length} niveles · {input.subjects.length} asignaturas · {input.classes} clases</span><button className="primary big" disabled={!input.name||!input.idea||!input.levels.length||!input.subjects.length} onClick={generate}>Generar propuesta ABP →</button></div></section>}
 {tab==='proyecto'&&<section className="panel"><div className="sectionhead"><div><span className="kicker">PROPUESTA GENERADA</span><h2>Diseño del proyecto</h2></div></div>{!project?<Empty text="Primero genera una propuesta desde Identificación."/>:<div className="generated">{[['description','Descripción general'],['question','Pregunta guía'],['problem','Problema o desafío'],['purpose','Propósito formativo'],['general','Objetivo general']].map(([k,l])=><Field key={k} label={l}><textarea rows="4" value={project[k]} onChange={e=>setProject({...project,[k]:e.target.value})}/></Field>)}<div className="card"><h3>Objetivos específicos</h3>{project.specifics.map((x,i)=><div className="objective" key={i}><b>{i+1}</b><textarea value={x} onChange={e=>{const a=[...project.specifics];a[i]=e.target.value;setProject({...project,specifics:a})}}/></div>)}</div><div className="note">Los objetivos usan verbos de acción y progresan desde la comprensión del desafío hacia el desarrollo, comunicación y evaluación del producto.</div></div>}</section>}
 {tab==='curriculo'&&<section className="panel"><div className="sectionhead"><div><span className="kicker">CURRÍCULO</span><h2>Objetivos curriculares</h2><p>Las sugerencias se ordenan por coincidencia entre niveles, asignaturas e idea del proyecto. Puedes aceptar, eliminar o editar cada propuesta.</p></div></div>{!project?<Empty text="Genera primero el proyecto."/>:<><div className="suggestions">{suggestions.map(o=><div className={'oa '+(oas.some(x=>x.id===o.id)?'chosen':'')} key={o.id}><div><span className="tag">{o.level} · {o.subject}</span><h3>{o.oa}</h3><p><b>Indicadores:</b> {o.indicators.join(' · ')}</p><p><b>Habilidades:</b> {o.skills.join(' · ')}</p></div><button onClick={()=>setOas(a=>a.some(x=>x.id===o.id)?a.filter(x=>x.id!==o.id):[...a,o])}>{oas.some(x=>x.id===o.id)?'✓ Incorporado':'+ Incorporar'}</button></div>)}</div><div className="note">Corpus curricular inicial demostrativo. La estructura está preparada para cargar el corpus oficial completo y sus metadatos de fuente.</div></>}</section>}
 {tab==='clases'&&<section className="panel"><div className="sectionhead"><div><span className="kicker">PLANIFICACIÓN</span><h2>Planificación clase a clase</h2><p>La cadena pedagógica es OA → actividad → evidencia → instrumento.</p></div><button className="ghost" onClick={regenerateClasses}>Regenerar clases</button></div>{!classes.length?<Empty text="Genera el proyecto para construir las clases."/>:<div className="classlist">{classes.map(c=><article className="classcard" key={c.id}><div className="classnum">{String(c.id).padStart(2,'0')}</div><div className="classbody"><span className="tag">{c.phase}</span><input value={c.name} onChange={e=>setClasses(a=>a.map(x=>x.id===c.id?{...x,name:e.target.value}:x))}/><label>Objetivo de la clase<textarea value={c.objective} onChange={e=>setClasses(a=>a.map(x=>x.id===c.id?{...x,objective:e.target.value}:x))}/></label><div className="mini"><div><b>Actividades</b><ul>{c.activities.map((x,i)=><li key={i}>{x}</li>)}</ul></div><div><b>Evidencia</b><p>{c.evidence}</p><b>Instrumento</b><p>{c.instrument}</p></div></div></div></article>)}</div>}</section>}
 {tab==='evaluacion'&&<section className="panel"><div className="sectionhead"><div><span className="kicker">EVALUACIÓN</span><h2>Evaluación para aprender</h2><p>La evaluación acompaña el proceso y utiliza evidencias variadas.</p></div></div><div className="evalgrid">{['Diagnóstico inicial','Evaluación formativa','Autoevaluación','Coevaluación','Evaluación docente','Evaluación del producto','Reflexión final'].map((x,i)=><div className="evalcard" key={x}><span>{String(i+1).padStart(2,'0')}</span><h3>{x}</h3><p>{['Activar saberes previos y detectar necesidades.','Retroalimentar avances y orientar decisiones.','Reconocer avances, dificultades y próximos pasos.','Ofrecer retroalimentación entre pares.','Valorar evidencias según criterios compartidos.','Valorar el resultado y su respuesta al desafío.','Analizar aprendizajes, decisiones y proyección.'][i]}</p><select defaultValue={i%3}><option value="0">Lista de cotejo</option><option value="1">Rúbrica</option><option value="2">Registro de observación</option></select></div>)}</div><div className="card"><h3>Principios de diseño evaluativo</h3><ul><li>Criterios conocidos antes de producir evidencias.</li><li>Retroalimentación durante el proceso, no solo al final.</li><li>Triangulación entre desempeño, producto y reflexión.</li><li>Oportunidades de autoevaluación y coevaluación.</li></ul></div></section>}
 {tab==='revision'&&<section className="panel"><div className="sectionhead"><div><span className="kicker">CONTROL DE CALIDAD</span><h2>Revisión de coherencia pedagógica</h2><p>Antes de exportar, revisa las relaciones fundamentales del proyecto.</p></div></div><div className="checks">{[['Desafío claro y relevante',!!project?.question],['Objetivo general responde al desafío',!!project?.general],['Hay exactamente 3 objetivos específicos',project?.specifics?.length===3],['Existen OAs curriculares incorporados',oas.length>0],['Cada clase tiene evidencia',classes.length>0&&classes.every(c=>c.evidence)],['Existe evaluación durante el proceso',true],['Las asignaturas tienen una función real',input.subjects.length>1],['Existe producto o resultado concreto',!!input.product||!!project?.general]].map(([x,ok])=><div className="check" key={x}><span className={ok?'ok':'warn'}>{ok?'✓':'!'}</span><div><b>{x}</b><small>{ok?'Revisado':'Requiere atención antes de exportar.'}</small></div></div>)}</div><div className="matrix"><h3>Matriz de coherencia</h3><div className="flow"><b>Desafío</b><i>→</i><b>Objetivo</b><i>→</i><b>OA</b><i>→</i><b>Actividad</b><i>→</i><b>Evidencia</b><i>→</i><b>Instrumento</b></div></div><div className="footerbar"><button className="primary big" disabled={!project} onClick={()=>exportWord({input,project,oas,classes})}>Descargar proyecto editable en Word</button></div></section>}
 </main><footer><span>Proyecto ABP Interdisciplinario · MVP</span><button onClick={()=>{localStorage.removeItem('abp-input');location.reload()}}>Limpiar datos locales</button></footer></div>
}
function Empty({text}){return <div className="empty">{text}</div>}
